name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: app/SeleniumDocker.sln
      Test_Project_Path: app/src/SeleniumDocker.csproj
      Wap_Project_Directory: app
      Wap_Project_Path: app/.wapproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          8.0.x

    - name: Install WinAppDriver
      run: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/WinAppDriver/releases/download/v1.2.99/WindowsApplicationDriver-1.2.99-win-x86.exe" -OutFile "C:\WindowsApplicationDriver.exe"
        Start-Process msiexec.exe -ArgumentList "/i C:\WindowsApplicationDriver.exe /quiet /norestart" -NoNewWindow -Wait

    - name: Enable Developer Mode for WinAppDriver
      run: Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" -Name "AllowDevelopmentWithoutDevLicense" -Value 1

    - name: Install TightVNC
      run: |
        Invoke-WebRequest -Uri "https://www.tightvnc.com/download/2.8.84/tightvnc-2.8.84-gpl-setup-64bit.msi" -OutFile "C:\tightvnc.msi"
        Start-Process msiexec.exe -ArgumentList "/i C:\tightvnc.msi /quiet /norestart" -NoNewWindow -Wait
        Set-ItemProperty -Path "HKLM:\SOFTWARE\TightVNC\Server" -Name "Password" -Value ([BitConverter]::ToString((New-Object Security.Cryptography.MD5CryptoServiceProvider).ComputeHash([System.Text.Encoding]::Unicode.GetBytes("your_password"))).Replace("-",""))
        New-ItemProperty -Path "HKLM:\SOFTWARE\TightVNC\Server" -Name "AcceptRFBConnections" -Value 1 -PropertyType DWord -Force
        Start-Service -Name "tvnserver"

    - name: Install Shift
      run: |
        Write-Output "Looking for Shift installer in the app/downloads directory..."
        $shiftInstaller = Get-ChildItem -Path "app/downloads" -Filter "Shift*.exe" | Select-Object -First 1
        if ($shiftInstaller) {
          Write-Output "Found Shift installer: $($shiftInstaller.FullName)"
          $process = Start-Process -FilePath $shiftInstaller.FullName -ArgumentList "/silent" -PassThru
          $process.WaitForExit()
          Write-Output "Shift installation completed."
        } else {
          throw "Shift installer is not available."
        }

    - name: Install Google Chrome
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "C:\chrome_installer.exe"
        Start-Process -FilePath "C:\chrome_installer.exe" -ArgumentList "/silent /install" -NoNewWindow -Wait

    - name: Install ChromeDriver
      run: |
        $chromeDriverVersion = Invoke-RestMethod -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
        Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$chromeDriverVersion/chromedriver_win32.zip" -OutFile "C:\chromedriver_win32.zip"
        Expand-Archive -Path "C:\chromedriver_win32.zip" -DestinationPath "C:\chromedriver"
        $env:Path += ";C:\chromedriver"

    - name: Set Time Zone to Pacific Time
      run: tzutil /s "Pacific Standard Time"

    - name: List files in app directory
      run: dir app

    - name: Create solution file
      run: |
        dotnet new sln -n SeleniumDocker --force
        dotnet sln app/SeleniumDocker.sln add app/src/SeleniumDocker.csproj
      working-directory: app

    - name: Restore dependencies
      run: dotnet restore app/SeleniumDocker.sln

    - name: Build
      run: dotnet build app/SeleniumDocker.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Verify Build Output
      run: dir app/src/bin/${{ matrix.configuration }}/net5.0

    - name: Execute unit tests
      run: dotnet test app/SeleniumDocker.sln --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install ngrok using Chocolatey
      run: choco install ngrok -y

    - name: Start ngrok
      run: ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}

    - name: Start ngrok TCP tunnel
      run: ngrok tcp 5900 &

    - name: Start Shift
      run: |
        $shiftPath = "$env:LOCALAPPDATA\Shift\chromium\shift.exe"
        if (Test-Path $shiftPath) {
          Start-Process -FilePath $shiftPath
          Write-Output "Shift started successfully."
        } else {
          Write-Output "Shift executable not found at $shiftPath."
        }

    - name: Check if Shift is running
      run: Get-Process -Name shift -ErrorAction SilentlyContinue

    - name: Take Screenshot
      run: |
        $screenshotPath = "C:\Users\runneradmin\Desktop\screenshot.png"
        Add-Type -AssemblyName System.Windows.Forms
        Add-Type -AssemblyName System.Drawing
        $bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
        $bitmap = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)
        $bitmap.Save($screenshotPath, [System.Drawing.Imaging.ImageFormat]::Png)
        Write-Output "Screenshot taken: $screenshotPath"

    - name: Upload Screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: C:\Users\runneradmin\Desktop\screenshot.png

    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Create the app package
      run: msbuild $env:Wap_Project_Path /p:Configuration=${{ matrix.configuration }} /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=$certificatePath /p:PackageCertificatePassword=${{ secrets.PFX_KEY }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    - name: Remove the pfx
      run: Remove-Item -path $certificatePath

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
